version: '3'

services:
  flyway:
    container_name: flyway
    image: flyway/flyway
    restart: always
    volumes:
      - ./data/flyway/project:/flyway/project
      - ./data/flyway/sql:/flyway/sql
    networks:
      - main
    entrypoint: >
      /bin/sh -c "
      sleep 30;
      flyway -configFiles=/flyway/project/flyway-target.toml migrate;
      "

networks:
  main:
    external: true
