version: "3"

services:
  postgres:
    container_name: pg_source
    image: postgres
    restart: always
    hostname: pg_source
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: source_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      # - ./data/flyway/sql/source/__init__.sql:/docker-entrypoint-initdb.d/__init__.sql
      - pg_source_data:/var/lib/postgresql/data
    networks:
      - main
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=1
               -c max_wal_senders=1

volumes:
  pg_source_data:

networks:
  main:
    external: true
