version: '3'

services:
  flyway:
    container_name: target_flyway
    image: flyway/flyway
    restart: always
    volumes:
      - ../flyway/project/target:/flyway/project/target
      - ../flyway/sql/target:/flyway/sql/target
    networks:
      - main
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      flyway -configFiles=/flyway/project/target/flyway-target.toml migrate;
      "

networks:
  main:
    external: true
