[environments.source]
url = "jdbc:postgresql://pg_source:5432/source_dev"
user = "admin"
password = "password"
locations = [
    "filesystem:/flyway/sql/source"
]

[flyway]
environment = "source"
baselineOnMigrate = true
group = true
